name: test-cron-cron
on:
  schedule:
    # runs tests every 2 minutes
    - cron: '*/5 * * * *'
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress scheduled tests 🌃
        uses: cypress-io/github-action@v4